# permissions for end users to view frappeworkpaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frappeworkpace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frappe-operator
    app.kubernetes.io/part-of: frappe-operator
    app.kubernetes.io/managed-by: kustomize
  name: frappeworkpace-viewer-role
rules:
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkpaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkpaces/status
  verbs:
  - get
