# permissions for end users to edit frappesites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frappesite-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frappe-operator
    app.kubernetes.io/part-of: frappe-operator
    app.kubernetes.io/managed-by: kustomize
  name: frappesite-editor-role
rules:
- apiGroups:
  - vyogo.tech
  resources:
  - frappesites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappesites/status
  verbs:
  - get
