---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - limitranges
  - persistentvolumeclaims
  - resourcequotas
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.mariadb.com
  resources:
  - databases
  - grants
  - mariadbs
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects/finalizers
  verbs:
  - update
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgv2.percona.com
  resources:
  - perconapgclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches
  - frappesites
  - frappeworkpaces
  - siteapikeys
  - siteapps
  - sitebackups
  - siteclientscripts
  - siteconfigs
  - sitecrons
  - sitecustomfields
  - sitedashboardcharts
  - sitedashboards
  - sitedomains
  - sitejobs
  - sitemigrations
  - sitepropertysetters
  - sitequotas
  - siterestores
  - siteroles
  - siteserverscripts
  - siteuserpermissions
  - siteusers
  - sitewebhooks
  - siteworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches/finalizers
  - frappesites/finalizers
  - frappeworkpaces/finalizers
  - siteapikeys/finalizers
  - siteapps/finalizers
  - sitebackups/finalizers
  - siteconfigs/finalizers
  - sitecrons/finalizers
  - sitedashboardcharts/finalizers
  - sitedashboards/finalizers
  - sitedomains/finalizers
  - sitejobs/finalizers
  - sitemigrations/finalizers
  - sitequotas/finalizers
  - siterestores/finalizers
  - siteroles/finalizers
  - siteusers/finalizers
  - siteworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches/status
  - frappesites/status
  - frappeworkpaces/status
  - siteapikeys/status
  - siteapps/status
  - sitebackups/status
  - siteclientscripts/status
  - siteconfigs/status
  - sitecrons/status
  - sitecustomfields/status
  - sitedashboardcharts/status
  - sitedashboards/status
  - sitedomains/status
  - sitejobs/status
  - sitemigrations/status
  - sitepropertysetters/status
  - sitequotas/status
  - siterestores/status
  - siteroles/status
  - siteserverscripts/status
  - siteuserpermissions/status
  - siteusers/status
  - sitewebhooks/status
  - siteworkspaces/status
  verbs:
  - get
  - patch
  - update
