apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: external-mock-site
  namespace: frappe
spec:
  siteName: external-mock.apps.crc.testing
  benchRef:
    name: autoscaling-hpa-bench
  dbConfig:
    provider: external
    host: 64.227.178.150
    port: "3306"
    connectionSecretRef:
      name: external-mariadb-creds
  skipInit: true
  apps:
    - erpnext
