apiVersion: vyogo.tech/v1
kind: FrappeBench
metadata:
  name: bench-test
  namespace: frappe
spec:
  frappeVersion: "15.0.0"
  imageConfig:
    repository: ghcr.io/vyogotech/frappe_custom_apps
    tag: v3.1.0
    pullPolicy: Always
  storageSize: 2Gi

  componentAutoscaling:
    gunicorn:
      enabled: false # Static replicas
      staticReplicas: 1
    
    nginx:
      enabled: false # Static replicas
      staticReplicas: 1
    
    worker-default:
      enabled: false # Static replicas
      staticReplicas: 0
    
    worker-short:
      enabled: false # Static replicas
      staticReplicas: 0
    
    worker-long:
      enabled: false
      staticReplicas: 0
      
    socketio:
      enabled: false
      staticReplicas: 0