apiVersion: vyogo.tech/v1
kind: FrappeSite
metadata:
  name: central-site
  namespace: frappe
spec:
  siteName: central-site.atxinvox.com.au
  adminPasswordSecretRef:
    name: central-site-admin-password
  benchRef:
    name: central-bench
    namespace: frappe

  # Database configuration
  dbConfig:
    provider: mariadb
    mode: shared
    mariadbRef:
      name: frappe-mariadb
      namespace: mariadb

  # Ingress configuration for OpenShift
  ingress:
    enabled: true
    className: nginx
  apps:
    - erpnext
  

