apiVersion: vyogo.tech/v1
kind: SiteRestore
metadata:
  name: restore-from-s3
  namespace: default
spec:
  site: e2e.example.com
  benchRef:
    name: e2e-bench
    namespace: default
  databaseBackupSource:
    s3:
      endpoint: "https://s3.amazonaws.com"
      bucket: my-frappe-backups
      key: "e2e.example.com/db.sql.gz"
      accessKeySecret:
        name: s3-credentials
        key: accessKey
      secretKeySecret:
        name: s3-credentials
        key: secretKey
  force: true
