apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: vyogodemo1
  namespace: frappe
spec:
  siteName: vyogodemo1.apps.crc.testing
  benchRef:
    name: vyogobench
  dbConfig:
    provider: external
    host: 64.227.178.150
    port: "3306"
    connectionSecretRef:
      name: external-mariadb-creds
  skipInit: true
  apps:
    - erpnext
    - brainwise
    - testing
