## Append samples you want in your CSV to this file as resources ##
resources:
- v1_frappebench.yaml
- v1_frappesite.yaml
- v1_siteapp.yaml
- v1_sitedomain.yaml
- v1_sitebackup.yaml
- v1_siterestore.yaml
- v1_sitemigration.yaml
- v1_siteuser.yaml
- v1_frappeworkpace.yaml
- v1_siteworkspace.yaml
- v1_sitedashboardchart.yaml
- v1_sitedashboard.yaml
- v1_sitejob.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
