# Example: Frappe site using shared MariaDB instance
# This is the most cost-effective option for multiple sites

apiVersion: vyogo.tech/v1alpha1
kind: FrappeBench
metadata:
  name: shared-bench
  namespace: default
spec:
  version: "v15.41.2"
  apps:
    - name: erpnext
      source:
        type: image
  componentReplicas:
    gunicorn: 2
    scheduler: 1
    workers:
      default: 2
      short: 1
      long: 1
  storageSize: "10Gi"
---
apiVersion: vyogo.tech/v1alpha1
kind: FrappeSite
metadata:
  name: site1
  namespace: default
spec:
  benchRef:
    name: shared-bench
  
  siteName: site1.example.com
  
  # Database configuration - shared mode
  dbConfig:
    provider: mariadb
    mode: shared
    mariadbRef:
      name: frappe-mariadb  # References the shared MariaDB instance
      namespace: default
  
  # Ingress configuration
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
  
  # TLS configuration
  tls:
    enabled: true
    issuer: letsencrypt-prod

  # Admin password will be auto-generated and stored in:
  # Secret: site1-admin (key: password)
  
  # Database credentials will be auto-generated by MariaDB Operator:
  # - Database: _<hash>_site1_example_com
  # - User: site1_user
  # - Password Secret: site1-db-password

