apiVersion: vyogo.tech/v1
kind: SiteApp
metadata:
  name: e2e-site-app-studio
  namespace: frappe
spec:
  siteRef:
    name: e2e-test-site
  appName: studio
  gitRepo: "https://github.com/frappe/studio"
